import { Horse } from "./components/HorseCard";

const horseData: Horse[] = [
    {
        horseId: 1,
        ratio: 2.13,
        horseName: "Silver Lightning",
        stake: 0,
        step: 0,
        profit: 1.20,
        isMultiBet: false,
    },
    {
        horseId: 2,
        ratio: 1.98,
        horseName: "Mayflower",
        stake: 0,
        step: 0,
        profit: 19.90,
        isMultiBet: false,
    },
    {
        horseId: 3,
        ratio: 2.45,
        horseName: "Starfire",
        stake: 0,
        step: 0,
        profit: 8.50,
        isMultiBet: false,
    },
    {
        horseId: 4,
        ratio: 2.20,
        horseName: "Midnight Runner",
        stake: 0,
        step: 0,
        profit: 12.75,
        isMultiBet: false,
    },
    {
        horseId: 5,
        ratio: 1.75,
        horseName: "Golden Spirit",
        stake: 0,
        step: 0,
        profit: 7.80,
        isMultiBet: false,
    },
    {
        horseId: 6,
        ratio: 2.60,
        horseName: "Red Thunder",
        stake: 0,
        step: 0,
        profit: 5.60,
        isMultiBet: false,
    },
    {
        horseId: 7,
        ratio: 2.15,
        horseName: "Rapid Storm",
        stake: 0,
        step: 0,
        profit: 9.25,
        isMultiBet: false,
    },
    {
        horseId: 8,
        ratio: 1.95,
        horseName: "Sapphire Dream",
        stake: 0,
        step: 0,
        profit: 14.30,
        isMultiBet: false,
    },
    {
        horseId: 9,
        ratio: 2.32,
        horseName: "Diamond Dash",
        stake: 0,
        step: 0,
        profit: 6.90,
        isMultiBet: false,
    },
    {
        horseId: 10,
        ratio: 2.06,
        horseName: "Lucky Charm",
        stake: 0,
        step: 0,
        profit: 3.40,
        isMultiBet: false,
    },
    {
        horseId: 11,
        ratio: 2.25,
        horseName: "Fast Finisher",
        stake: 0,
        step: 0,
        profit: 11.10,
        isMultiBet: false,
    },
    {
        horseId: 12,
        ratio: 2.11,
        horseName: "Moonlit Magic",
        stake: 0,
        step: 0,
        profit: 6.60,
        isMultiBet: false,
    }
];

export default horseData;
